<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>mefriendapi-2-0</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MeFriendApi.Domain\MeFriendApi.Domain.csproj" />
    <ProjectReference Include="..\MeFriendApi.Services\MeFriendApi.Services.csproj" />
  </ItemGroup>

</Project>
